# Removed version as it's obsolete in Docker Compose v2

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: mindbridge-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mindbridge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mindbridge"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Main Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mindbridge-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password123@database:5432/mindbridge
      - SESSION_SECRET=your-super-secret-session-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database migration service (runs once and exits)
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mindbridge-migrate
    environment:
      - DATABASE_URL=postgresql://postgres:password123@database:5432/mindbridge
    depends_on:
      database:
        condition: service_healthy
    command: ["npm", "run", "db:push"]
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  default:
    name: mindbridge-network